// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiAuthPasswordResetConfirmCreateData, ApiAuthPasswordResetConfirmCreateResponses, ApiAuthPasswordResetOtpConfirmCreateData, ApiAuthPasswordResetOtpConfirmCreateResponses, ApiAuthPasswordResetOtpRequestCreateData, ApiAuthPasswordResetOtpRequestCreateResponses, ApiAuthPasswordResetRequestCreateData, ApiAuthPasswordResetRequestCreateResponses, ApiAuthRegisterCreateData, ApiAuthRegisterCreateResponses, ApiAuthResendOtpCreateData, ApiAuthResendOtpCreateResponses, ApiAuthTokenCreateData, ApiAuthTokenCreateResponses, ApiAuthTokenRefreshCreateData, ApiAuthTokenRefreshCreateResponses, ApiAuthVerifyOtpCreateData, ApiAuthVerifyOtpCreateResponses, ApiProjectsCreateData, ApiProjectsCreateResponses, ApiProjectsDestroyData, ApiProjectsDestroyResponses, ApiProjectsListData, ApiProjectsListResponses, ApiProjectsPartialUpdateData, ApiProjectsPartialUpdateResponses, ApiProjectsRetrieveData, ApiProjectsRetrieveResponses, ApiProjectsUpdateData, ApiProjectsUpdateResponses, ApiUsersChangePasswordCreateData, ApiUsersChangePasswordCreateResponses, ApiUsersListData, ApiUsersListResponses, ApiUsersMePartialUpdateData, ApiUsersMePartialUpdateResponses, ApiUsersMeRetrieveData, ApiUsersMeRetrieveResponses, ApiUsersPartialUpdateData, ApiUsersPartialUpdateResponses, ApiUsersRetrieveData, ApiUsersRetrieveResponses, ApiUsersUpdateData, ApiUsersUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Reset password using valid OTP code.
 */
export const apiAuthPasswordResetOtpConfirmCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthPasswordResetOtpConfirmCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthPasswordResetOtpConfirmCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/password-reset-otp/confirm/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Request password reset and send OTP code via email.
 */
export const apiAuthPasswordResetOtpRequestCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthPasswordResetOtpRequestCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthPasswordResetOtpRequestCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/password-reset-otp/request/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Reset password using valid token.
 */
export const apiAuthPasswordResetConfirmCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthPasswordResetConfirmCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthPasswordResetConfirmCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/password-reset/confirm/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Request password reset and send email with reset token.
 */
export const apiAuthPasswordResetRequestCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthPasswordResetRequestCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthPasswordResetRequestCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/password-reset/request/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * API endpoint for user registration with OTP email verification.
 */
export const apiAuthRegisterCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthRegisterCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthRegisterCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/register/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Resend OTP code to user's email.
 */
export const apiAuthResendOtpCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthResendOtpCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthResendOtpCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/resend-otp/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Obtain JWT access and refresh tokens using email and password. Email must be verified.
 */
export const apiAuthTokenCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthTokenCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthTokenCreateResponses, unknown, ThrowOnError>({
        url: '/api/auth/token/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * JWT token refresh view (uses default SimpleJWT behavior).
 */
export const apiAuthTokenRefreshCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthTokenRefreshCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthTokenRefreshCreateResponses, unknown, ThrowOnError>({
        url: '/api/auth/token/refresh/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Verify OTP code and mark user email as verified.
 */
export const apiAuthVerifyOtpCreate = <ThrowOnError extends boolean = false>(options: Options<ApiAuthVerifyOtpCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiAuthVerifyOtpCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/verify-otp/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all projects for the authenticated user
 *
 * Returns a paginated list of projects owned by the current user
 */
export const apiProjectsList = <ThrowOnError extends boolean = false>(options?: Options<ApiProjectsListData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiProjectsListResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/projects/',
        ...options
    });
};

/**
 * ViewSet for managing projects.
 *
 * All endpoints require authentication.
 * Projects are filtered to show only those owned by the current user.
 */
export const apiProjectsCreate = <ThrowOnError extends boolean = false>(options: Options<ApiProjectsCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiProjectsCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/projects/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * ViewSet for managing projects.
 *
 * All endpoints require authentication.
 * Projects are filtered to show only those owned by the current user.
 */
export const apiProjectsDestroy = <ThrowOnError extends boolean = false>(options: Options<ApiProjectsDestroyData, ThrowOnError>) => {
    return (options.client ?? client).delete<ApiProjectsDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/projects/{uuid}/',
        ...options
    });
};

/**
 * ViewSet for managing projects.
 *
 * All endpoints require authentication.
 * Projects are filtered to show only those owned by the current user.
 */
export const apiProjectsRetrieve = <ThrowOnError extends boolean = false>(options: Options<ApiProjectsRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiProjectsRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/projects/{uuid}/',
        ...options
    });
};

/**
 * ViewSet for managing projects.
 *
 * All endpoints require authentication.
 * Projects are filtered to show only those owned by the current user.
 */
export const apiProjectsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<ApiProjectsPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<ApiProjectsPartialUpdateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/projects/{uuid}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * ViewSet for managing projects.
 *
 * All endpoints require authentication.
 * Projects are filtered to show only those owned by the current user.
 */
export const apiProjectsUpdate = <ThrowOnError extends boolean = false>(options: Options<ApiProjectsUpdateData, ThrowOnError>) => {
    return (options.client ?? client).put<ApiProjectsUpdateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/projects/{uuid}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const apiUsersList = <ThrowOnError extends boolean = false>(options?: Options<ApiUsersListData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiUsersListResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/',
        ...options
    });
};

export const apiUsersRetrieve = <ThrowOnError extends boolean = false>(options: Options<ApiUsersRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiUsersRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options
    });
};

export const apiUsersPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<ApiUsersPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<ApiUsersPartialUpdateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const apiUsersUpdate = <ThrowOnError extends boolean = false>(options: Options<ApiUsersUpdateData, ThrowOnError>) => {
    return (options.client ?? client).put<ApiUsersUpdateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Change user password with old password verification.
 */
export const apiUsersChangePasswordCreate = <ThrowOnError extends boolean = false>(options: Options<ApiUsersChangePasswordCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiUsersChangePasswordCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/change-password/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get or update the current user's profile.
 */
export const apiUsersMeRetrieve = <ThrowOnError extends boolean = false>(options?: Options<ApiUsersMeRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiUsersMeRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/me/',
        ...options
    });
};

/**
 * Get or update the current user's profile.
 */
export const apiUsersMePartialUpdate = <ThrowOnError extends boolean = false>(options?: Options<ApiUsersMePartialUpdateData, ThrowOnError>) => {
    return (options?.client ?? client).patch<ApiUsersMePartialUpdateResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/me/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};
