# Generated by Django 5.2.7 on 2025-10-24 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('code', models.CharField(max_length=6, verbose_name='OTP code')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Email Verification OTP',
                'verbose_name_plural': 'Email Verification OTPs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', '-created'], name='users_email_user_id_5d2307_idx'), models.Index(fields=['code', 'is_used'], name='users_email_code_a9dac1_idx')],
            },
        ),
    ]
