// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Custom JWT serializer that uses email and checks email verification.
 */
export type EmailTokenObtainPairRequest = {
    email: string;
    password: string;
};

/**
 * Serializer for OTP email verification.
 */
export type OtpVerification = {
    email: string;
    code: string;
};

/**
 * Serializer for OTP email verification.
 */
export type OtpVerificationRequest = {
    email: string;
    code: string;
};

/**
 * Serializer for changing password (authenticated users).
 */
export type PasswordChangeRequest = {
    old_password: string;
    new_password: string;
};

/**
 * Serializer for password reset confirmation.
 */
export type PasswordResetConfirm = {
    token: string;
};

/**
 * Serializer for password reset confirmation.
 */
export type PasswordResetConfirmRequest = {
    token: string;
};

/**
 * Serializer for password reset request.
 */
export type PasswordResetRequest = {
    email: string;
};

/**
 * Serializer for password reset request.
 */
export type PasswordResetRequestRequest = {
    email: string;
};

export type PatchedProjectRequest = {
    name?: string;
    description?: string;
    status?: StatusEnum;
    priority?: PriorityEnum;
    start_date?: string | null;
    due_date?: string | null;
};

export type PatchedUserRequest = {
    first_name?: string;
    last_name?: string;
    /**
     * Email address
     */
    email?: string;
    avatar?: Blob | File | null;
};

/**
 * * `1` - Low
 * * `2` - Medium
 * * `3` - High
 * * `4` - Critical
 */
export type PriorityEnum = 1 | 2 | 3 | 4;

export type Project = {
    readonly uuid: string;
    name: string;
    description?: string;
    readonly owner: string;
    readonly owner_email: string;
    status?: StatusEnum;
    priority?: PriorityEnum;
    start_date?: string | null;
    due_date?: string | null;
    readonly is_overdue: boolean;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Separate serializer for creation to handle owner assignment
 */
export type ProjectCreate = {
    readonly uuid: string;
    name: string;
    description?: string;
    readonly owner: string;
    readonly owner_email: string;
    status?: StatusEnum;
    priority?: PriorityEnum;
    start_date?: string | null;
    due_date?: string | null;
    readonly is_overdue: boolean;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Separate serializer for creation to handle owner assignment
 */
export type ProjectCreateRequest = {
    name: string;
    description?: string;
    status?: StatusEnum;
    priority?: PriorityEnum;
    start_date?: string | null;
    due_date?: string | null;
};

export type ProjectRequest = {
    name: string;
    description?: string;
    status?: StatusEnum;
    priority?: PriorityEnum;
    start_date?: string | null;
    due_date?: string | null;
};

/**
 * Serializer for resending OTP to unverified email.
 */
export type ResendOtp = {
    email: string;
};

/**
 * Serializer for resending OTP to unverified email.
 */
export type ResendOtpRequest = {
    email: string;
};

/**
 * * `draft` - Draft
 * * `active` - Active
 * * `completed` - Completed
 * * `archived` - Archived
 */
export type StatusEnum = 'draft' | 'active' | 'completed' | 'archived';

export type TokenObtainPair = {
    readonly access: string;
    readonly refresh: string;
};

export type TokenRefresh = {
    readonly access: string;
    refresh: string;
};

export type TokenRefreshRequest = {
    refresh: string;
};

export type User = {
    first_name: string;
    last_name: string;
    /**
     * Email address
     */
    email: string;
    readonly url: string;
    avatar?: string | null;
};

/**
 * Serializer for user registration with password validation.
 */
export type UserRegistration = {
    /**
     * Email address
     */
    email: string;
    first_name: string;
    last_name: string;
};

/**
 * Serializer for user registration with password validation.
 */
export type UserRegistrationRequest = {
    /**
     * Email address
     */
    email: string;
    first_name: string;
    last_name: string;
};

export type UserRequest = {
    first_name: string;
    last_name: string;
    /**
     * Email address
     */
    email: string;
    avatar?: Blob | File | null;
};

/**
 * Serializer for password reset confirmation.
 */
export type PasswordResetConfirmRequestWritable = {
    token: string;
    password: string;
};

export type ProjectWritable = {
    name: string;
    description?: string;
    status?: StatusEnum;
    priority?: PriorityEnum;
    start_date?: string | null;
    due_date?: string | null;
};

/**
 * Separate serializer for creation to handle owner assignment
 */
export type ProjectCreateWritable = {
    name: string;
    description?: string;
    status?: StatusEnum;
    priority?: PriorityEnum;
    start_date?: string | null;
    due_date?: string | null;
};

export type TokenRefreshWritable = {
    refresh: string;
};

export type UserWritable = {
    first_name: string;
    last_name: string;
    /**
     * Email address
     */
    email: string;
    avatar?: string | null;
};

/**
 * Serializer for user registration with password validation.
 */
export type UserRegistrationRequestWritable = {
    /**
     * Email address
     */
    email: string;
    password: string;
    first_name: string;
    last_name: string;
};

export type ApiAuthPasswordResetConfirmCreateData = {
    body: PasswordResetConfirmRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset/confirm/';
};

export type ApiAuthPasswordResetConfirmCreateResponses = {
    200: PasswordResetConfirm;
};

export type ApiAuthPasswordResetConfirmCreateResponse = ApiAuthPasswordResetConfirmCreateResponses[keyof ApiAuthPasswordResetConfirmCreateResponses];

export type ApiAuthPasswordResetRequestCreateData = {
    body: PasswordResetRequestRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset/request/';
};

export type ApiAuthPasswordResetRequestCreateResponses = {
    200: PasswordResetRequest;
};

export type ApiAuthPasswordResetRequestCreateResponse = ApiAuthPasswordResetRequestCreateResponses[keyof ApiAuthPasswordResetRequestCreateResponses];

export type ApiAuthRegisterCreateData = {
    body: UserRegistrationRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/register/';
};

export type ApiAuthRegisterCreateResponses = {
    201: UserRegistration;
};

export type ApiAuthRegisterCreateResponse = ApiAuthRegisterCreateResponses[keyof ApiAuthRegisterCreateResponses];

export type ApiAuthResendOtpCreateData = {
    body: ResendOtpRequest;
    path?: never;
    query?: never;
    url: '/api/auth/resend-otp/';
};

export type ApiAuthResendOtpCreateResponses = {
    200: ResendOtp;
};

export type ApiAuthResendOtpCreateResponse = ApiAuthResendOtpCreateResponses[keyof ApiAuthResendOtpCreateResponses];

export type ApiAuthTokenCreateData = {
    body: EmailTokenObtainPairRequest;
    path?: never;
    query?: never;
    url: '/api/auth/token/';
};

export type ApiAuthTokenCreateResponses = {
    200: TokenObtainPair;
};

export type ApiAuthTokenCreateResponse = ApiAuthTokenCreateResponses[keyof ApiAuthTokenCreateResponses];

export type ApiAuthTokenRefreshCreateData = {
    body: TokenRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/token/refresh/';
};

export type ApiAuthTokenRefreshCreateResponses = {
    200: TokenRefresh;
};

export type ApiAuthTokenRefreshCreateResponse = ApiAuthTokenRefreshCreateResponses[keyof ApiAuthTokenRefreshCreateResponses];

export type ApiAuthVerifyOtpCreateData = {
    body: OtpVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/auth/verify-otp/';
};

export type ApiAuthVerifyOtpCreateResponses = {
    200: OtpVerification;
};

export type ApiAuthVerifyOtpCreateResponse = ApiAuthVerifyOtpCreateResponses[keyof ApiAuthVerifyOtpCreateResponses];

export type ApiProjectsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Filter by project status
         */
        status?: 'active' | 'archived' | 'completed' | 'draft';
    };
    url: '/api/projects/';
};

export type ApiProjectsListResponses = {
    200: Array<Project>;
};

export type ApiProjectsListResponse = ApiProjectsListResponses[keyof ApiProjectsListResponses];

export type ApiProjectsCreateData = {
    body: ProjectCreateRequest;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type ApiProjectsCreateResponses = {
    201: ProjectCreate;
};

export type ApiProjectsCreateResponse = ApiProjectsCreateResponses[keyof ApiProjectsCreateResponses];

export type ApiProjectsDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/projects/{uuid}/';
};

export type ApiProjectsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ApiProjectsDestroyResponse = ApiProjectsDestroyResponses[keyof ApiProjectsDestroyResponses];

export type ApiProjectsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/projects/{uuid}/';
};

export type ApiProjectsRetrieveResponses = {
    200: Project;
};

export type ApiProjectsRetrieveResponse = ApiProjectsRetrieveResponses[keyof ApiProjectsRetrieveResponses];

export type ApiProjectsPartialUpdateData = {
    body?: PatchedProjectRequest;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/projects/{uuid}/';
};

export type ApiProjectsPartialUpdateResponses = {
    200: Project;
};

export type ApiProjectsPartialUpdateResponse = ApiProjectsPartialUpdateResponses[keyof ApiProjectsPartialUpdateResponses];

export type ApiProjectsUpdateData = {
    body: ProjectRequest;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/projects/{uuid}/';
};

export type ApiProjectsUpdateResponses = {
    200: Project;
};

export type ApiProjectsUpdateResponse = ApiProjectsUpdateResponses[keyof ApiProjectsUpdateResponses];

export type ApiUsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type ApiUsersListResponses = {
    200: Array<User>;
};

export type ApiUsersListResponse = ApiUsersListResponses[keyof ApiUsersListResponses];

export type ApiUsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersRetrieveResponses = {
    200: User;
};

export type ApiUsersRetrieveResponse = ApiUsersRetrieveResponses[keyof ApiUsersRetrieveResponses];

export type ApiUsersPartialUpdateData = {
    body?: PatchedUserRequest;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersPartialUpdateResponses = {
    200: User;
};

export type ApiUsersPartialUpdateResponse = ApiUsersPartialUpdateResponses[keyof ApiUsersPartialUpdateResponses];

export type ApiUsersUpdateData = {
    body: UserRequest;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersUpdateResponses = {
    200: User;
};

export type ApiUsersUpdateResponse = ApiUsersUpdateResponses[keyof ApiUsersUpdateResponses];

export type ApiUsersChangePasswordCreateData = {
    body: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/api/users/change-password/';
};

export type ApiUsersChangePasswordCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ApiUsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type ApiUsersMeRetrieveResponses = {
    200: User;
};

export type ApiUsersMeRetrieveResponse = ApiUsersMeRetrieveResponses[keyof ApiUsersMeRetrieveResponses];

export type ApiUsersMePartialUpdateData = {
    body?: PatchedUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type ApiUsersMePartialUpdateResponses = {
    200: User;
};

export type ApiUsersMePartialUpdateResponse = ApiUsersMePartialUpdateResponses[keyof ApiUsersMePartialUpdateResponses];
