#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd /app/backend

python manage.py collectstatic --noinput

exec gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app/backend -k uvicorn_worker.UvicornWorker
